# Generated by Django 2.0.4 on 2018-06-01 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=17)),
                ('fecha_alta_proveedor', models.DateField(default=django.utils.timezone.now)),
                ('telefono_1', models.CharField(max_length=20)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_proveedores',
                'managed': False,
            },
        ),
    ]
