# Generated by Django 2.0.4 on 2018-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('año_fabricacion', models.CharField(max_length=4)),
                ('capacidad_btu', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'tbl_modelo_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tbl_tipo_equipo',
                'managed': False,
            },
        ),
    ]
